
package com.zillus.coronadiary.ui;

import com.flowingcode.vaadin.addons.ironicons.IronIcons;
import com.rapidclipse.framework.server.data.renderer.RenderedComponent;
import com.vaadin.flow.component.ClickEvent;
import com.vaadin.flow.component.ComponentEvent;
import com.vaadin.flow.component.ComponentEventListener;
import com.vaadin.flow.component.UI;
import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.button.ButtonVariant;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.zillus.coronadiary.domain.MedicalEntity;


public class GenColMedicalDetail extends VerticalLayout implements RenderedComponent<MedicalEntity>
{

	private MedicalEntity medical;
	
	/**
	 *
	 */
	public GenColMedicalDetail()
	{
		super();
		this.initUI();
	}

	@Override
	public void renderComponent(final MedicalEntity value)
	{
		this.medical = value;
		
	}

	/**
	 * Event handler delegate method for the {@link Button} {@link #btnEdit}.
	 *
	 * @see ComponentEventListener#onComponentEvent(ComponentEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void btnEdit_onClick(final ClickEvent<Button> event)
	{
		UI.getCurrent().getSession().setAttribute(MedicalEntity.class, this.medical);
	}
	
	/* WARNING: Do NOT edit!<br>The content of this method is always regenerated by the UI designer. */
	// <generated-code name="initUI">
	private void initUI()
	{
		this.btnEdit = new Button();

		this.btnEdit.addThemeVariants(ButtonVariant.LUMO_SMALL, ButtonVariant.LUMO_TERTIARY);
		this.btnEdit.setIcon(IronIcons.SEARCH.create());

		this.btnEdit.setSizeUndefined();
		this.add(this.btnEdit);
		this.setSizeUndefined();

		this.btnEdit.addClickListener(this::btnEdit_onClick);
	} // </generated-code>

	// <generated-code name="variables">
	private Button btnEdit;
	// </generated-code>
	
}
