/*******************************************************************************
 * Copyright 2021 Frank Zillus
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 ******************************************************************************/
package com.zillus.coronadiary.ui;

import com.vaadin.flow.component.html.H1;
import com.vaadin.flow.component.html.H2;
import com.vaadin.flow.component.orderedlayout.FlexComponent;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.router.Route;
import com.zillus.coronadiary.HasTitle;
import com.zillus.coronadiary.dal.PersonDAO;
import com.zillus.coronadiary.dal.TreatmentDAO;


@Route(value = "", layout = MainLayout.class)
public class HomeView extends VerticalLayout implements HasTitle
{
	public HomeView()
	{
		super();
		this.initUI();
		this.initData();
	}

	/**
	 * Inits the data.
	 */
	private void initData()
	{
		this.h2Items.setText("Number of diary items: " + TreatmentDAO.findAll().size());
		this.h2Patient.setText("Number of persons registered: " + PersonDAO.findAll().size());
	}

	@Override
	public String getTitle()
	{
		return "Home";
	}

	/* WARNING: Do NOT edit!<br>The content of this method is always regenerated by the UI designer. */
	// <generated-code name="initUI">
	private void initUI()
	{
		this.headLine  = new H1();
		this.h22       = new H2();
		this.h2Items   = new H2();
		this.h2Patient = new H2();

		this.setSpacing(false);
		this.headLine.setText("Corona Diary");
		this.headLine.getStyle().set("font-family", "times");
		this.headLine.getStyle().set("color", "Orange");
		this.h22.setText("by Frank Zillus 2021");
		this.h2Items.setText("none");
		this.h2Patient.setText("none");

		this.headLine.setSizeUndefined();
		this.h22.setSizeUndefined();
		this.h2Items.setSizeUndefined();
		this.h2Patient.setSizeUndefined();
		this.add(this.headLine, this.h22, this.h2Items, this.h2Patient);
		this.setHorizontalComponentAlignment(FlexComponent.Alignment.CENTER, this.headLine);
		this.setSizeUndefined();
	} // </generated-code>

	// <generated-code name="variables">
	private H1 headLine;
	private H2 h22, h2Items, h2Patient;
	// </generated-code>

}
