
package com.zillus.coronadiary.ui;

import com.flowingcode.vaadin.addons.ironicons.IronIcons;
import com.rapidclipse.framework.server.data.renderer.CaptionRenderer;
import com.rapidclipse.framework.server.resources.CaptionUtils;
import com.vaadin.flow.component.ClickEvent;
import com.vaadin.flow.component.ComponentEvent;
import com.vaadin.flow.component.ComponentEventListener;
import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.button.ButtonVariant;
import com.vaadin.flow.component.grid.Grid;
import com.vaadin.flow.component.orderedlayout.HorizontalLayout;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.router.Route;
import com.zillus.coronadiary.HasTitle;
import com.zillus.coronadiary.dal.PersonDAO;
import com.zillus.coronadiary.domain.PatientEntity;
import com.zillus.coronadiary.ui.popup.PatientPopup;


@Route(value = "patient", layout = MainLayout.class)
public class PatientView extends VerticalLayout implements HasTitle
{
	public PatientView()
	{
		super();
		this.initUI();

		this.gridPatient.setItems(PersonDAO.filterAllPatients());
	}

	@Override
	public String getTitle()
	{
		return "Patient";
	}

	/**
	 * Event handler delegate method for the {@link Button} {@link #addBtn}.
	 *
	 * @see ComponentEventListener#onComponentEvent(ComponentEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void addBtn_onClick(final ClickEvent<Button> event)
	{
		new PatientPopup()
			.setSavedCallback(() -> {
				this.refresh();
			}).open();
	}

	/**
	 * Refresh.
	 */
	public void refresh()
	{
		this.gridPatient.getDataProvider().refreshAll();
	}

	/* WARNING: Do NOT edit!<br>The content of this method is always regenerated by the UI designer. */
	// <generated-code name="initUI">
	private void initUI()
	{
		this.horizontalLayout = new HorizontalLayout();
		this.addBtn           = new Button();
		this.cancelBtn        = new Button();
		this.gridPatient      = new Grid<>(PatientEntity.class, false);

		this.addBtn.setText("Patient");
		this.addBtn.addThemeVariants(ButtonVariant.LUMO_SUCCESS);
		this.addBtn.setIcon(IronIcons.ADD.create());
		this.cancelBtn.setText("Cancel");
		this.cancelBtn.addThemeVariants(ButtonVariant.LUMO_ERROR);
		this.cancelBtn.setIcon(IronIcons.CANCEL.create());
		this.gridPatient.addColumn(PatientEntity::getName).setKey("name")
			.setHeader(CaptionUtils.resolveCaption(PatientEntity.class, "name")).setSortable(true);
		this.gridPatient.addColumn(PatientEntity::getBirthday).setKey("birthday")
			.setHeader(CaptionUtils.resolveCaption(PatientEntity.class, "birthday")).setSortable(true);
		this.gridPatient.addColumn(PatientEntity::getAdress1).setKey("adress1")
			.setHeader(CaptionUtils.resolveCaption(PatientEntity.class, "adress1")).setSortable(true);
		this.gridPatient.addColumn(PatientEntity::getAdress2).setKey("adress2")
			.setHeader(CaptionUtils.resolveCaption(PatientEntity.class, "adress2")).setSortable(true);
		this.gridPatient.addColumn(PatientEntity::getCity).setKey("city")
			.setHeader(CaptionUtils.resolveCaption(PatientEntity.class, "city")).setSortable(true);
		this.gridPatient.addColumn(PatientEntity::getZipCode).setKey("zipCode")
			.setHeader(CaptionUtils.resolveCaption(PatientEntity.class, "zipCode")).setSortable(true);
		this.gridPatient.addColumn(new CaptionRenderer<>(PatientEntity::getGender)).setKey("gender")
			.setHeader(CaptionUtils.resolveCaption(PatientEntity.class, "gender")).setSortable(true);
		this.gridPatient.setSelectionMode(Grid.SelectionMode.SINGLE);

		this.addBtn.setSizeUndefined();
		this.cancelBtn.setSizeUndefined();
		this.horizontalLayout.add(this.addBtn, this.cancelBtn);
		this.horizontalLayout.setWidthFull();
		this.horizontalLayout.setHeight(null);
		this.gridPatient.setWidthFull();
		this.gridPatient.setHeight(null);
		this.add(this.horizontalLayout, this.gridPatient);
		this.setFlexGrow(1.0, this.gridPatient);
		this.setWidthFull();
		this.setHeight(null);

		this.addBtn.addClickListener(this::addBtn_onClick);
	} // </generated-code>

	// <generated-code name="variables">
	private Button              addBtn, cancelBtn;
	private HorizontalLayout    horizontalLayout;
	private Grid<PatientEntity> gridPatient;
	// </generated-code>

}
