
package com.zillus.coronadiary.ui.popup;

import java.time.LocalDate;

import com.flowingcode.vaadin.addons.ironicons.IronIcons;
import com.rapidclipse.framework.server.resources.CaptionUtils;
import com.rapidclipse.framework.server.ui.ItemLabelGeneratorFactory;
import com.vaadin.flow.component.ClickEvent;
import com.vaadin.flow.component.ComponentEvent;
import com.vaadin.flow.component.ComponentEventListener;
import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.button.ButtonVariant;
import com.vaadin.flow.component.checkbox.Checkbox;
import com.vaadin.flow.component.combobox.ComboBox;
import com.vaadin.flow.component.datepicker.DatePicker;
import com.vaadin.flow.component.dialog.Dialog;
import com.vaadin.flow.component.formlayout.FormLayout;
import com.vaadin.flow.component.formlayout.FormLayout.FormItem;
import com.vaadin.flow.component.html.Label;
import com.vaadin.flow.component.orderedlayout.HorizontalLayout;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.component.textfield.TextField;
import com.vaadin.flow.data.binder.Binder;
import com.vaadin.flow.data.binder.ValidationException;
import com.zillus.coronadiary.dal.TreatmentDAO;
import com.zillus.coronadiary.domain.VaccinationEntity;
import com.zillus.coronadiary.domain.enums.Vaccine;


public class VaccinationPopup extends Dialog
{

	/** The vaccination entity. */
	private final VaccinationEntity vaccinationEntity;

	/** The on oklistener. */
	private Runnable onOklistener;

	/**
	 *
	 */
	public VaccinationPopup()
	{
		super();
		this.initUI();
		this.initCombos();

		this.vaccinationEntity = new VaccinationEntity();
		this.binder.readBean(this.vaccinationEntity);
	}

	/**
	 * Inits the combos.
	 */
	private void initCombos()
	{
		this.cmbVaccine.setItems(Vaccine.values());
		this.dateDate.setValue(LocalDate.now());
	}

	/**
	 * Save binder.
	 */
	private void saveBinder()
	{
		try
		{
			this.binder.writeBean(this.vaccinationEntity);
			TreatmentDAO.addEntity(this.vaccinationEntity);
			this.onOklistener.run();
		}
		catch(final ValidationException e)
		{
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	/**
	 * Sets the saved callback.
	 *
	 * @param listener
	 *            the listener
	 * @return the vaccination popup
	 */
	public VaccinationPopup setSavedCallback(final Runnable listener)
	{
		this.onOklistener = listener;
		return this;
	}

	/**
	 * Event handler delegate method for the {@link Button} {@link #btnCancel}.
	 *
	 * @see ComponentEventListener#onComponentEvent(ComponentEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void btnCancel_onClick(final ClickEvent<Button> event)
	{
		this.close();
	}

	/**
	 * Event handler delegate method for the {@link Button} {@link #btnSave}.
	 *
	 * @see ComponentEventListener#onComponentEvent(ComponentEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void btnSave_onClick(final ClickEvent<Button> event)
	{
		this.saveBinder();
		this.close();
	}

	/* WARNING: Do NOT edit!<br>The content of this method is always regenerated by the UI designer. */
	// <generated-code name="initUI">
	private void initUI()
	{
		this.verticalLayout         = new VerticalLayout();
		this.horizontalLayoutBtnBar = new HorizontalLayout();
		this.btnSave                = new Button();
		this.btnCancel              = new Button();
		this.form                   = new FormLayout();
		this.formItem               = new FormItem();
		this.lblDate                = new Label();
		this.dateDate               = new DatePicker();
		this.formItem2              = new FormItem();
		this.lblName                = new Label();
		this.txtName                = new TextField();
		this.formItem3              = new FormItem();
		this.lblType                = new Label();
		this.cmbVaccine             = new ComboBox<>();
		this.formItem4              = new FormItem();
		this.lblBooster             = new Label();
		this.chkBooster             = new Checkbox();
		this.binder                 = new Binder<>();

		this.verticalLayout.setPadding(false);
		this.btnSave.setText("Save");
		this.btnSave.addThemeVariants(ButtonVariant.LUMO_SUCCESS);
		this.btnSave.setIcon(IronIcons.SAVE.create());
		this.btnCancel.setText("Cancel");
		this.btnCancel.addThemeVariants(ButtonVariant.LUMO_ERROR);
		this.btnCancel.setIcon(IronIcons.CANCEL.create());
		this.form
			.setResponsiveSteps(new FormLayout.ResponsiveStep("0px", 1, FormLayout.ResponsiveStep.LabelsPosition.TOP));
		this.lblDate.setText("Vaccination Date");
		this.lblName.setText("Vaccine");
		this.lblType.setText("Vaccine Type");
		this.cmbVaccine.setItemLabelGenerator(ItemLabelGeneratorFactory.NonNull(CaptionUtils::resolveCaption));
		this.lblBooster.setText("Is Booster");
		this.chkBooster.setLabel("Booster Vacc");

		this.binder.forField(this.dateDate).bind(VaccinationEntity::getDate, VaccinationEntity::setDate);
		this.binder.forField(this.txtName).asRequired().withNullRepresentation("").bind(VaccinationEntity::getName,
			VaccinationEntity::setName);
		this.binder.forField(this.chkBooster).withNullRepresentation(false).bind(VaccinationEntity::getBooster,
			VaccinationEntity::setBooster);
		this.binder.forField(this.cmbVaccine).bind(VaccinationEntity::getVaccine, VaccinationEntity::setVaccine);

		this.btnSave.setWidthFull();
		this.btnSave.setHeight(null);
		this.btnCancel.setWidthFull();
		this.btnCancel.setHeight(null);
		this.horizontalLayoutBtnBar.add(this.btnSave, this.btnCancel);
		this.lblDate.setSizeUndefined();
		this.lblDate.getElement().setAttribute("slot", "label");
		this.dateDate.setWidthFull();
		this.dateDate.setHeight(null);
		this.formItem.add(this.lblDate, this.dateDate);
		this.lblName.setSizeUndefined();
		this.lblName.getElement().setAttribute("slot", "label");
		this.txtName.setWidthFull();
		this.txtName.setHeight(null);
		this.formItem2.add(this.lblName, this.txtName);
		this.lblType.setSizeUndefined();
		this.lblType.getElement().setAttribute("slot", "label");
		this.cmbVaccine.setWidthFull();
		this.cmbVaccine.setHeight(null);
		this.formItem3.add(this.lblType, this.cmbVaccine);
		this.lblBooster.setSizeUndefined();
		this.lblBooster.getElement().setAttribute("slot", "label");
		this.chkBooster.setWidthFull();
		this.chkBooster.setHeight(null);
		this.formItem4.add(this.lblBooster, this.chkBooster);
		this.form.add(this.formItem, this.formItem2, this.formItem3, this.formItem4);
		this.horizontalLayoutBtnBar.setWidthFull();
		this.horizontalLayoutBtnBar.setHeight(null);
		this.form.setWidthFull();
		this.form.setHeight(null);
		this.verticalLayout.add(this.horizontalLayoutBtnBar, this.form);
		this.verticalLayout.setSizeUndefined();
		this.add(this.verticalLayout);
		this.setWidth("90%");
		this.setHeight("80%");

		this.btnSave.addClickListener(this::btnSave_onClick);
		this.btnCancel.addClickListener(this::btnCancel_onClick);
	} // </generated-code>

	// <generated-code name="variables">
	private FormLayout                form;
	private Checkbox                  chkBooster;
	private Button                    btnSave, btnCancel;
	private DatePicker                dateDate;
	private ComboBox<Vaccine>         cmbVaccine;
	private Binder<VaccinationEntity> binder;
	private VerticalLayout            verticalLayout;
	private HorizontalLayout          horizontalLayoutBtnBar;
	private Label                     lblDate, lblName, lblType, lblBooster;
	private TextField                 txtName;
	private FormItem                  formItem, formItem2, formItem3, formItem4;
	// </generated-code>

}
